FORMAT: 1A

# Vinyl DB
An API to save your vinyls.

# Group Labels
Labels related resources of the **Vinyl DB API**

## Labels Collection [/labels]
### List all Labels [GET]
+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "Blue Note"
            },
            {
                "id": 2,
                "name": "Elektra Records"
            },
            {
                "id": 3,
                "name": "Verve"
            },
            {
                "id": 4,
                "name": "Motown Records"
            },
            {
                "id": 5,
                "name": "Geffen Records"
            }
        ]


### Create a Label [POST]
+ Request (application/json)

        {
            "name": "Capitol"
        }

+ Response 201 (application/json)

        {
            "id": 6,
            "name": "Capitol"
        }

## Label [/labels/{id}]
A single Label object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Label to perform action with. Has example value.

### Retrieve a Label [GET]
+ Response 200 (application/json)

        {
            "id": 4,
            "name": "Motown Records"
        }

### Remove a Label [DELETE]
+ Response 204
